#!/bin/sh

if [ ! -f /etc/config/luci ]; then
	touch /etc/config/luci
fi

if ! uci -q get luci.themes >/dev/null; then
	uci set luci.themes=internal
	uci commit luci
fi

if ! uci -q get luci.themes.Proton2025 >/dev/null; then
	uci set luci.themes.Proton2025="/luci-static/proton2025"
	uci commit luci
fi

exit 0
