#!/bin/sh

if [ "$PKG_UPGRADE" != 1 ]; then
	uci get luci.themes.Proton2025 >/dev/null 2>&1 || \
	uci batch <<-EOF
		set luci.themes.Proton2025=/luci-static/proton2025
		set luci.main.mediaurlbase=/luci-static/proton2025
		commit luci
	EOF
fi

exit 0
